/**
 * CC-24 PA-review correction §4 (further corrected in a follow-up pass):
 * generates `CC-24-PILOT-002-DEPTH-REVIEW-INPUT.json` -- a deterministic,
 * ANSWER-FREE review input for the Project Architect's own
 * qualification-depth decision on all 15 selected requirements, ahead of
 * any pilot-002.
 *
 * [Corrected] The prior version embedded `new Date().toISOString()` and
 * relied on its own test simply IGNORING that field to call the output
 * "deterministic" -- which is not the same thing as actually being
 * deterministic. This version contains NO wall-clock field at all.
 * Instead it carries DETERMINISTIC source-state metadata a caller can
 * use to prove two runs (or a later re-verification) drew from the
 * identical repository state: `schemaVersion` (a fixed string, bumped
 * only on an intentional shape change) and three content hashes --
 * `blindTargetContentHash` (the sealed target manifest's own hash, as
 * returned by the adapter's guarded read), `sourcePlanHash` (the
 * corrected clean plan's canonical-JSON hash), and
 * `selectionDefinitionHash` (a hash of the fixed 15-ID list itself).
 * Two calls against the same repository state now produce genuinely
 * byte-identical JSON, with nothing for a test to have to ignore.
 *
 * [Corrected] `rawQualificationWording` is renamed `acquisitionTargetWording`.
 * This field is the sealed blind-target manifest's own proposition text
 * for one `acquisitionTargetId` -- it is NOT independently verified as
 * the awarding body's own official published qualification wording
 * (that verification, if ever needed, is separate work this script does
 * not perform), so it must never be labelled as such.
 *
 * Imports ONLY: the frozen blind target manifest (via the Unit-202
 * adapter, through a real guarded read), the Unit-202 adapter's own
 * audit metadata, the corrected clean plan (canonical authority policy
 * already applied), and the fixed 15-ID selection definition. NEVER
 * reads pilot-001 artifacts, historical benchmarks, source dossiers, old
 * claims, learner assertions, lessons/storyboards, or private
 * calibration material -- none of those are imported anywhere on this
 * script's module graph (mechanically proven alongside the rest of the
 * clean pilot-preparation path by clean-plan.test.ts's import-graph scan,
 * which covers every file in this directory).
 *
 * Every `paDepthReview` field is explicitly `null` -- this script makes
 * NO depth, curriculum, or pedagogy decision, and infers nothing. The
 * Project Architect's actual decisions are recorded in a SEPARATE,
 * human-authored artifact, `CC-24-PILOT-002-PA-DEPTH-DECISION.json`
 * (not generated by this script), which cites this file's own SHA-256
 * so the reviewed input can never silently drift from the decision made
 * against it.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { hashContent, type EvidenceRequirement, type KnowledgeEvidencePlanResult, type KnowledgeTarget } from "@alp/technical-evidence-engine";

import { buildUnit202PlanningInput, type AdapterAuditEntry } from "../unit202-evidence-acquisition-preflight/unit202-adapter.ts";
import { buildCleanPlan } from "./clean-plan.ts";
import { SELECTED_EVIDENCE_REQUIREMENT_IDS } from "./pilot-selection.ts";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, "..", "..", "..");
const outDir = path.join(repoRoot, "reports", "backtests", "unit202-blind-acquisition-run");

export const DEPTH_REVIEW_INPUT_SCHEMA_VERSION = "1.0.0";

export interface QualificationProvenanceEntry {
  readonly knowledgeTargetId: string;
  readonly acquisitionTargetId: string;
  readonly ac: string;
  /** The sealed blind-target manifest's own proposition text for this acquisitionTargetId -- NOT independently verified as the awarding body's official published qualification wording. */
  readonly acquisitionTargetWording: string;
}

export interface EmptyPaDepthReview {
  readonly qualificationPerformanceVerb: null;
  readonly minimumSufficientDepth: null;
  readonly maximumJustifiedDepth: null;
  readonly excludedEnrichment: null;
  readonly assessmentPerformanceExpected: null;
  readonly depthEvidenceBasis: null;
  readonly depthVerdict: null;
  readonly architectNotes: null;
  readonly approvedAt: null;
}

export interface DepthReviewItem {
  readonly evidenceRequirementId: string;
  readonly sourceKnowledgeTargetIds: readonly string[];
  readonly qualificationProvenance: readonly QualificationProvenanceEntry[];
  readonly requirementMode: string;
  readonly specificationMode: string;
  readonly requirementText: string;
  readonly evidenceQuestion: string | null;
  readonly requiredCoverageDimensions: readonly string[];
  readonly permittedAuthorityClasses: readonly string[];
  readonly acceptanceCriteria: string;
  readonly calibratedSupportingPerformance: unknown;
  readonly representativeExemplar: boolean;
  readonly reusesFoundationalProcedureIds: readonly string[] | null;
  readonly paDepthReview: EmptyPaDepthReview;
}

export interface DepthReviewInput {
  readonly schemaVersion: string;
  readonly purpose: string;
  readonly status: "PENDING_PROJECT_ARCHITECT_DEPTH_REVIEW";
  readonly blindTargetContentHash: string;
  readonly sourcePlanHash: string;
  readonly selectionDefinitionHash: string;
  readonly expectedItemCount: number;
  readonly items: readonly DepthReviewItem[];
}

const EMPTY_PA_DEPTH_REVIEW: EmptyPaDepthReview = {
  qualificationPerformanceVerb: null,
  minimumSufficientDepth: null,
  maximumJustifiedDepth: null,
  excludedEnrichment: null,
  assessmentPerformanceExpected: null,
  depthEvidenceBasis: null,
  depthVerdict: null,
  architectNotes: null,
  approvedAt: null,
};

/** Mirrors freeze-selection.ts's own canonical-JSON convention for `sourcePlanHash`, so this script's notion of "the plan's hash" is computed the same way the pilot's own producer scripts compute it -- never a second, silently-different definition. */
function sourcePlanHashFor(plan: KnowledgeEvidencePlanResult): string {
  const canonical = JSON.stringify({ requirementCount: plan.requirements.length, requirements: plan.requirements, structuralSatisfactions: plan.structuralSatisfactions }, null, 2) + "\n";
  return hashContent(canonical);
}

/** Deterministic -- calling this twice against the same repository state produces byte-identical output. No wall-clock field exists anywhere in the return value; `schemaVersion` plus the three content hashes are the only "when/what state" metadata, and all four are themselves pure functions of repository content. */
export function buildDepthReviewInput(): DepthReviewInput {
  const { input, audit, blindTargetsContentHash } = buildUnit202PlanningInput();
  const plan = buildCleanPlan();

  const auditByTargetId = new Map<string, AdapterAuditEntry>();
  for (const a of audit) auditByTargetId.set(a.knowledgeTargetId, a);
  const targetById = new Map<string, KnowledgeTarget>();
  for (const t of input.knowledgeTargets) targetById.set(t.knowledgeTargetId, t);
  const requirementById = new Map<string, EvidenceRequirement>();
  for (const r of plan.requirements) requirementById.set(r.evidenceRequirementId, r);

  const items: DepthReviewItem[] = SELECTED_EVIDENCE_REQUIREMENT_IDS.map((id) => {
    const r = requirementById.get(id);
    if (!r) throw new Error(`buildDepthReviewInput: "${id}" is not present in the corrected clean plan -- refusing to generate an incomplete depth-review input.`);

    const qualificationProvenance: QualificationProvenanceEntry[] = r.sourceKnowledgeTargetIds.map((ktId) => {
      const a = auditByTargetId.get(ktId);
      if (!a) throw new Error(`buildDepthReviewInput: no adapter audit entry found for source knowledge target "${ktId}" (required for "${id}").`);
      return { knowledgeTargetId: ktId, acquisitionTargetId: a.acquisitionTargetId, ac: a.ac, acquisitionTargetWording: a.rawProposition };
    });

    const reusesFoundationalProcedureIds = r.sourceKnowledgeTargetIds.reduce<string[]>((acc, ktId) => {
      const t = targetById.get(ktId);
      if (t?.reusesFoundationalProcedureIds) acc.push(...t.reusesFoundationalProcedureIds);
      return acc;
    }, []);

    return {
      evidenceRequirementId: r.evidenceRequirementId,
      sourceKnowledgeTargetIds: r.sourceKnowledgeTargetIds,
      qualificationProvenance,
      requirementMode: r.requirementMode,
      specificationMode: r.specificationMode,
      requirementText: r.requirementText,
      evidenceQuestion: r.evidenceQuestion,
      requiredCoverageDimensions: r.requiredCoverageDimensions,
      permittedAuthorityClasses: r.sourceAuthorityClasses,
      acceptanceCriteria: r.acceptanceCriteria,
      calibratedSupportingPerformance: r.calibratedSupportingPerformance,
      representativeExemplar: r.representativeExemplar,
      reusesFoundationalProcedureIds: reusesFoundationalProcedureIds.length > 0 ? reusesFoundationalProcedureIds : null,
      paDepthReview: EMPTY_PA_DEPTH_REVIEW,
    };
  });

  return {
    schemaVersion: DEPTH_REVIEW_INPUT_SCHEMA_VERSION,
    purpose: "Answer-free, deterministic review input for the Project Architect's qualification-depth decision on all 15 CC-24 pilot-selected requirements, ahead of the next acquisition attempt. Generated only from the sealed blind target, the Unit-202 adapter/audit metadata, the corrected clean plan, and the fixed 15-ID selection definition -- never from the prior invalidated acquisition run's own artifacts, historical benchmarks, source dossiers, old claims, learner assertions, lessons/storyboards, or private calibration material.",
    status: "PENDING_PROJECT_ARCHITECT_DEPTH_REVIEW",
    blindTargetContentHash: blindTargetsContentHash,
    sourcePlanHash: sourcePlanHashFor(plan),
    selectionDefinitionHash: hashContent(JSON.stringify(SELECTED_EVIDENCE_REQUIREMENT_IDS)),
    expectedItemCount: SELECTED_EVIDENCE_REQUIREMENT_IDS.length,
    items,
  };
}

if (path.resolve(__filename) === path.resolve(process.argv[1] ?? "")) {
  mkdirSync(outDir, { recursive: true });
  const output = buildDepthReviewInput();
  const outputJson = JSON.stringify(output, null, 2) + "\n";
  writeFileSync(path.join(outDir, "CC-24-PILOT-002-DEPTH-REVIEW-INPUT.json"), outputJson, "utf-8");
  console.log("CC-24-PILOT-002-DEPTH-REVIEW-INPUT.json written:", output.items.length, "items, status:", output.status, "hash:", hashContent(outputJson));
}
