/**
 * CC-05D: governed-content mirror of
 * scripts/visual-governance/data/canonical-variants.ts's output -- apps/mobile
 * must never import scripts/visual-governance directly (the same content-
 * authoring-tooling boundary rule scripts/content/README.md already
 * states, mirrored identically here, and the same pattern
 * apps/mobile/src/lib/proving-content/unit202-proving-fixture.ts already
 * established for CC-05C's governed content).
 *
 * Every entry here is mechanically cross-checked byte-for-byte against
 * the real builder output by
 * scripts/visual-governance/check-mobile-canonical-variants-fixture.test.ts
 * (content-authoring tooling, permitted to import both sides). If the
 * real canonical-variant data changes, that test fails until this file
 * is updated to match -- it cannot silently drift.
 *
 * CC-11.3: regenerated in full, straight from the real builders (a
 * throwaway script, run once and discarded -- the same
 * generate-not-hand-type approach CC-11's own comment here documents),
 * to guarantee byte-for-byte parity after adding 9 new diagram
 * blueprints (66 total canonical variants, up from 31) and correcting
 * the ohmmeter canonical variant's connection_style from "series" to
 * "isolated" (see instrument.measurement_connection's own DiagramBlueprint
 * parameter comment in cc05a-pedagogy-unit202.ts).
 */

import type { CanonicalVariant } from "@alp/content-schema";

export const CC05D_CONTENT_RELEASE = "cc05d-visual-governance-pilot-v1";

export const CANONICAL_VARIANTS: readonly CanonicalVariant[] = [
  {
    variantId: "visual-contract.series-circuit-current-direction@1::component_count=2,mode=both,show_current_arrow=true,show_values=false::both",
    contractId: "visual-contract.series-circuit-current-direction",
    contractVersion: 1,
    diagramBlueprintId: "circuit.series_resistors",
    mode: "both",
    parameters: { component_count: 2, show_values: false, show_current_arrow: true },
    labels: ["R1", "R2"],
    revealProps: {},
  },
  {
    variantId: "visual-contract.series-circuit-current-direction@1::component_count=3,mode=both,show_current_arrow=true,show_values=false::both",
    contractId: "visual-contract.series-circuit-current-direction",
    contractVersion: 1,
    diagramBlueprintId: "circuit.series_resistors",
    mode: "both",
    parameters: { component_count: 3, show_values: false, show_current_arrow: true },
    labels: ["R1", "R2", "R3"],
    revealProps: {},
  },
  {
    variantId: "visual-contract.series-circuit-current-direction@1::component_count=4,mode=both,show_current_arrow=true,show_values=false::both",
    contractId: "visual-contract.series-circuit-current-direction",
    contractVersion: 1,
    diagramBlueprintId: "circuit.series_resistors",
    mode: "both",
    parameters: { component_count: 4, show_values: false, show_current_arrow: true },
    labels: ["R1", "R2", "R3", "R4"],
    revealProps: {},
  },
  {
    variantId: "visual-contract.parallel-circuit-branches@1::branch_count=2,mode=both,show_branch_current_arrows=true,show_values=false::both",
    contractId: "visual-contract.parallel-circuit-branches",
    contractVersion: 1,
    diagramBlueprintId: "circuit.parallel_resistors",
    mode: "both",
    parameters: { branch_count: 2, show_values: false, show_branch_current_arrows: true },
    labels: ["R1", "R2"],
    revealProps: {},
  },
  {
    variantId: "visual-contract.parallel-circuit-branches@1::branch_count=3,mode=both,show_branch_current_arrows=true,show_values=false::both",
    contractId: "visual-contract.parallel-circuit-branches",
    contractVersion: 1,
    diagramBlueprintId: "circuit.parallel_resistors",
    mode: "both",
    parameters: { branch_count: 3, show_values: false, show_branch_current_arrows: true },
    labels: ["R1", "R2", "R3"],
    revealProps: {},
  },
  {
    variantId: "visual-contract.parallel-circuit-branches@1::branch_count=4,mode=both,show_branch_current_arrows=true,show_values=false::both",
    contractId: "visual-contract.parallel-circuit-branches",
    contractVersion: 1,
    diagramBlueprintId: "circuit.parallel_resistors",
    mode: "both",
    parameters: { branch_count: 4, show_values: false, show_branch_current_arrows: true },
    labels: ["R1", "R2", "R3", "R4"],
    revealProps: {},
  },
  {
    variantId:
      "visual-contract.right-hand-grip-rule@1::current_direction=into_page,field_rotation=clockwise,mode=teaching,show_field_arrows=true::teaching",
    contractId: "visual-contract.right-hand-grip-rule",
    contractVersion: 1,
    diagramBlueprintId: "magnetic.field_conductor_direction",
    mode: "teaching",
    parameters: { current_direction: "into_page", show_field_arrows: true },
    labels: ["conductor"],
    revealProps: { field_rotation: "clockwise" },
  },
  {
    variantId: "visual-contract.right-hand-grip-rule@1::current_direction=into_page,mode=assessment,show_field_arrows=true::assessment",
    contractId: "visual-contract.right-hand-grip-rule",
    contractVersion: 1,
    diagramBlueprintId: "magnetic.field_conductor_direction",
    mode: "assessment",
    parameters: { current_direction: "into_page", show_field_arrows: true },
    labels: ["conductor"],
    revealProps: {},
  },
  {
    variantId:
      "visual-contract.right-hand-grip-rule@1::current_direction=out_of_page,field_rotation=counterclockwise,mode=teaching,show_field_arrows=true::teaching",
    contractId: "visual-contract.right-hand-grip-rule",
    contractVersion: 1,
    diagramBlueprintId: "magnetic.field_conductor_direction",
    mode: "teaching",
    parameters: { current_direction: "out_of_page", show_field_arrows: true },
    labels: ["conductor"],
    revealProps: { field_rotation: "counterclockwise" },
  },
  {
    variantId: "visual-contract.right-hand-grip-rule@1::current_direction=out_of_page,mode=assessment,show_field_arrows=true::assessment",
    contractId: "visual-contract.right-hand-grip-rule",
    contractVersion: 1,
    diagramBlueprintId: "magnetic.field_conductor_direction",
    mode: "assessment",
    parameters: { current_direction: "out_of_page", show_field_arrows: true },
    labels: ["conductor"],
    revealProps: {},
  },
  {
    variantId:
      "visual-contract.motor-principle-force@1::current_direction=into_page,force_direction=down,mode=teaching,pole_labels=N_S_horizontal,show_force_arrow=true::teaching",
    contractId: "visual-contract.motor-principle-force",
    contractVersion: 1,
    diagramBlueprintId: "motor.force_field_current",
    mode: "teaching",
    parameters: { pole_labels: "N_S_horizontal", current_direction: "into_page", show_force_arrow: true },
    labels: ["conductor"],
    revealProps: { force_direction: "down" },
  },
  {
    variantId:
      "visual-contract.motor-principle-force@1::current_direction=into_page,mode=assessment,pole_labels=N_S_horizontal,show_force_arrow=true::assessment",
    contractId: "visual-contract.motor-principle-force",
    contractVersion: 1,
    diagramBlueprintId: "motor.force_field_current",
    mode: "assessment",
    parameters: { pole_labels: "N_S_horizontal", current_direction: "into_page", show_force_arrow: true },
    labels: ["conductor"],
    revealProps: {},
  },
  {
    variantId:
      "visual-contract.motor-principle-force@1::current_direction=out_of_page,force_direction=up,mode=teaching,pole_labels=N_S_horizontal,show_force_arrow=true::teaching",
    contractId: "visual-contract.motor-principle-force",
    contractVersion: 1,
    diagramBlueprintId: "motor.force_field_current",
    mode: "teaching",
    parameters: { pole_labels: "N_S_horizontal", current_direction: "out_of_page", show_force_arrow: true },
    labels: ["conductor"],
    revealProps: { force_direction: "up" },
  },
  {
    variantId:
      "visual-contract.motor-principle-force@1::current_direction=out_of_page,mode=assessment,pole_labels=N_S_horizontal,show_force_arrow=true::assessment",
    contractId: "visual-contract.motor-principle-force",
    contractVersion: 1,
    diagramBlueprintId: "motor.force_field_current",
    mode: "assessment",
    parameters: { pole_labels: "N_S_horizontal", current_direction: "out_of_page", show_force_arrow: true },
    labels: ["conductor"],
    revealProps: {},
  },
  {
    variantId:
      "visual-contract.motor-principle-force@1::current_direction=into_page,force_direction=left,mode=teaching,pole_labels=N_S_vertical,show_force_arrow=true::teaching",
    contractId: "visual-contract.motor-principle-force",
    contractVersion: 1,
    diagramBlueprintId: "motor.force_field_current",
    mode: "teaching",
    parameters: { pole_labels: "N_S_vertical", current_direction: "into_page", show_force_arrow: true },
    labels: ["conductor"],
    revealProps: { force_direction: "left" },
  },
  {
    variantId:
      "visual-contract.motor-principle-force@1::current_direction=into_page,mode=assessment,pole_labels=N_S_vertical,show_force_arrow=true::assessment",
    contractId: "visual-contract.motor-principle-force",
    contractVersion: 1,
    diagramBlueprintId: "motor.force_field_current",
    mode: "assessment",
    parameters: { pole_labels: "N_S_vertical", current_direction: "into_page", show_force_arrow: true },
    labels: ["conductor"],
    revealProps: {},
  },
  {
    variantId:
      "visual-contract.motor-principle-force@1::current_direction=out_of_page,force_direction=right,mode=teaching,pole_labels=N_S_vertical,show_force_arrow=true::teaching",
    contractId: "visual-contract.motor-principle-force",
    contractVersion: 1,
    diagramBlueprintId: "motor.force_field_current",
    mode: "teaching",
    parameters: { pole_labels: "N_S_vertical", current_direction: "out_of_page", show_force_arrow: true },
    labels: ["conductor"],
    revealProps: { force_direction: "right" },
  },
  {
    variantId:
      "visual-contract.motor-principle-force@1::current_direction=out_of_page,mode=assessment,pole_labels=N_S_vertical,show_force_arrow=true::assessment",
    contractId: "visual-contract.motor-principle-force",
    contractVersion: 1,
    diagramBlueprintId: "motor.force_field_current",
    mode: "assessment",
    parameters: { pole_labels: "N_S_vertical", current_direction: "out_of_page", show_force_arrow: true },
    labels: ["conductor"],
    revealProps: {},
  },
  {
    variantId: "visual-contract.series-parallel-mixed-topology@1::branch_arrangement=series_of_parallel,mode=both,show_values=false::both",
    contractId: "visual-contract.series-parallel-mixed-topology",
    contractVersion: 1,
    diagramBlueprintId: "circuit.series_parallel_mixed",
    mode: "both",
    parameters: { branch_arrangement: "series_of_parallel", show_values: false },
    labels: ["R1", "R2", "R3"],
    revealProps: {},
  },
  {
    variantId: "visual-contract.series-parallel-mixed-topology@1::branch_arrangement=parallel_of_series,mode=both,show_values=false::both",
    contractId: "visual-contract.series-parallel-mixed-topology",
    contractVersion: 1,
    diagramBlueprintId: "circuit.series_parallel_mixed",
    mode: "both",
    parameters: { branch_arrangement: "parallel_of_series", show_values: false },
    labels: ["R1", "R2", "R3", "R4"],
    revealProps: {},
  },
  {
    variantId: "visual-contract.ac-waveform-sine@1::cycles_shown=2,mode=both,show_peak_line=false,show_period_marker=false,show_rms_line=false::both",
    contractId: "visual-contract.ac-waveform-sine",
    contractVersion: 1,
    diagramBlueprintId: "graph.waveform_sine",
    mode: "both",
    parameters: { show_peak_line: false, show_rms_line: false, show_period_marker: false, cycles_shown: 2 },
    labels: [],
    revealProps: {},
  },
  {
    variantId: "visual-contract.ac-waveform-sine@1::cycles_shown=2,mode=both,show_peak_line=true,show_period_marker=false,show_rms_line=false::both",
    contractId: "visual-contract.ac-waveform-sine",
    contractVersion: 1,
    diagramBlueprintId: "graph.waveform_sine",
    mode: "both",
    parameters: { show_peak_line: true, show_rms_line: false, show_period_marker: false, cycles_shown: 2 },
    labels: [],
    revealProps: {},
  },
  {
    variantId: "visual-contract.ac-waveform-sine@1::cycles_shown=2,mode=both,show_peak_line=true,show_period_marker=false,show_rms_line=true::both",
    contractId: "visual-contract.ac-waveform-sine",
    contractVersion: 1,
    diagramBlueprintId: "graph.waveform_sine",
    mode: "both",
    parameters: { show_peak_line: true, show_rms_line: true, show_period_marker: false, cycles_shown: 2 },
    labels: [],
    revealProps: {},
  },
  {
    variantId: "visual-contract.ac-waveform-sine@1::cycles_shown=2,mode=both,show_peak_line=true,show_period_marker=true,show_rms_line=true::both",
    contractId: "visual-contract.ac-waveform-sine",
    contractVersion: 1,
    diagramBlueprintId: "graph.waveform_sine",
    mode: "both",
    parameters: { show_peak_line: true, show_rms_line: true, show_period_marker: true, cycles_shown: 2 },
    labels: [],
    revealProps: {},
  },
  {
    variantId: "visual-contract.ac-waveform-sine@1::cycles_shown=1,mode=both,show_peak_line=true,show_period_marker=true,show_rms_line=true::both",
    contractId: "visual-contract.ac-waveform-sine",
    contractVersion: 1,
    diagramBlueprintId: "graph.waveform_sine",
    mode: "both",
    parameters: { show_peak_line: true, show_rms_line: true, show_period_marker: true, cycles_shown: 1 },
    labels: [],
    revealProps: {},
  },
  {
    variantId: "visual-contract.ac-waveform-sine@1::cycles_shown=3,mode=both,show_peak_line=true,show_period_marker=true,show_rms_line=true::both",
    contractId: "visual-contract.ac-waveform-sine",
    contractVersion: 1,
    diagramBlueprintId: "graph.waveform_sine",
    mode: "both",
    parameters: { show_peak_line: true, show_rms_line: true, show_period_marker: true, cycles_shown: 3 },
    labels: [],
    revealProps: {},
  },
  {
    variantId: "visual-contract.instrument-measurement-connection@1::connection_style=parallel,instrument_type=voltmeter,mode=both::both",
    contractId: "visual-contract.instrument-measurement-connection",
    contractVersion: 1,
    diagramBlueprintId: "instrument.measurement_connection",
    mode: "both",
    parameters: { instrument_type: "voltmeter", connection_style: "parallel" },
    labels: [],
    revealProps: {},
  },
  {
    variantId: "visual-contract.instrument-measurement-connection@1::connection_style=series,instrument_type=voltmeter,mode=both::both",
    contractId: "visual-contract.instrument-measurement-connection",
    contractVersion: 1,
    diagramBlueprintId: "instrument.measurement_connection",
    mode: "both",
    parameters: { instrument_type: "voltmeter", connection_style: "series" },
    labels: [],
    revealProps: {},
  },
  {
    variantId: "visual-contract.instrument-measurement-connection@1::connection_style=series,instrument_type=ammeter,mode=both::both",
    contractId: "visual-contract.instrument-measurement-connection",
    contractVersion: 1,
    diagramBlueprintId: "instrument.measurement_connection",
    mode: "both",
    parameters: { instrument_type: "ammeter", connection_style: "series" },
    labels: [],
    revealProps: {},
  },
  {
    variantId: "visual-contract.instrument-measurement-connection@1::connection_style=parallel,instrument_type=ammeter,mode=both::both",
    contractId: "visual-contract.instrument-measurement-connection",
    contractVersion: 1,
    diagramBlueprintId: "instrument.measurement_connection",
    mode: "both",
    parameters: { instrument_type: "ammeter", connection_style: "parallel" },
    labels: [],
    revealProps: {},
  },
  {
    variantId: "visual-contract.instrument-measurement-connection@1::connection_style=isolated,instrument_type=ohmmeter,mode=both::both",
    contractId: "visual-contract.instrument-measurement-connection",
    contractVersion: 1,
    diagramBlueprintId: "instrument.measurement_connection",
    mode: "both",
    parameters: { instrument_type: "ohmmeter", connection_style: "isolated" },
    labels: [],
    revealProps: {},
  },
  // ---------------------------------------------------------------------
  // CC-11.3: whole-course instructional visual coverage closeout.
  // ---------------------------------------------------------------------
  {
    variantId: "visual-contract.lever-class-arrangement@1::lever_class=class_1,mode=both,show_distances=false::both",
    contractId: "visual-contract.lever-class-arrangement",
    contractVersion: 1,
    diagramBlueprintId: "mechanical.lever_arrangement",
    mode: "both",
    parameters: { lever_class: "class_1", show_distances: false },
    labels: [],
    revealProps: {},
  },
  {
    variantId: "visual-contract.lever-class-arrangement@1::lever_class=class_1,mode=both,show_distances=true::both",
    contractId: "visual-contract.lever-class-arrangement",
    contractVersion: 1,
    diagramBlueprintId: "mechanical.lever_arrangement",
    mode: "both",
    parameters: { lever_class: "class_1", show_distances: true },
    labels: [],
    revealProps: {},
  },
  {
    variantId: "visual-contract.lever-class-arrangement@1::lever_class=class_2,mode=both,show_distances=false::both",
    contractId: "visual-contract.lever-class-arrangement",
    contractVersion: 1,
    diagramBlueprintId: "mechanical.lever_arrangement",
    mode: "both",
    parameters: { lever_class: "class_2", show_distances: false },
    labels: [],
    revealProps: {},
  },
  {
    variantId: "visual-contract.lever-class-arrangement@1::lever_class=class_2,mode=both,show_distances=true::both",
    contractId: "visual-contract.lever-class-arrangement",
    contractVersion: 1,
    diagramBlueprintId: "mechanical.lever_arrangement",
    mode: "both",
    parameters: { lever_class: "class_2", show_distances: true },
    labels: [],
    revealProps: {},
  },
  {
    variantId: "visual-contract.lever-class-arrangement@1::lever_class=class_3,mode=both,show_distances=false::both",
    contractId: "visual-contract.lever-class-arrangement",
    contractVersion: 1,
    diagramBlueprintId: "mechanical.lever_arrangement",
    mode: "both",
    parameters: { lever_class: "class_3", show_distances: false },
    labels: [],
    revealProps: {},
  },
  {
    variantId: "visual-contract.lever-class-arrangement@1::lever_class=class_3,mode=both,show_distances=true::both",
    contractId: "visual-contract.lever-class-arrangement",
    contractVersion: 1,
    diagramBlueprintId: "mechanical.lever_arrangement",
    mode: "both",
    parameters: { lever_class: "class_3", show_distances: true },
    labels: [],
    revealProps: {},
  },
  {
    variantId: "visual-contract.gear-mesh-ratio@1::mode=both,size_ratio=driven_larger::both",
    contractId: "visual-contract.gear-mesh-ratio",
    contractVersion: 1,
    diagramBlueprintId: "mechanical.gear_mesh",
    mode: "both",
    parameters: { size_ratio: "driven_larger" },
    labels: [],
    revealProps: {},
  },
  {
    variantId: "visual-contract.gear-mesh-ratio@1::mode=both,size_ratio=driven_smaller::both",
    contractId: "visual-contract.gear-mesh-ratio",
    contractVersion: 1,
    diagramBlueprintId: "mechanical.gear_mesh",
    mode: "both",
    parameters: { size_ratio: "driven_smaller" },
    labels: [],
    revealProps: {},
  },
  {
    variantId: "visual-contract.gear-mesh-ratio@1::mode=both,size_ratio=equal::both",
    contractId: "visual-contract.gear-mesh-ratio",
    contractVersion: 1,
    diagramBlueprintId: "mechanical.gear_mesh",
    mode: "both",
    parameters: { size_ratio: "equal" },
    labels: [],
    revealProps: {},
  },
  {
    variantId: "visual-contract.pulley-fixed-vs-movable@1::arrangement=fixed,mode=both::both",
    contractId: "visual-contract.pulley-fixed-vs-movable",
    contractVersion: 1,
    diagramBlueprintId: "mechanical.pulley_arrangement",
    mode: "both",
    parameters: { arrangement: "fixed" },
    labels: [],
    revealProps: {},
  },
  {
    variantId: "visual-contract.pulley-fixed-vs-movable@1::arrangement=movable,mode=both::both",
    contractId: "visual-contract.pulley-fixed-vs-movable",
    contractVersion: 1,
    diagramBlueprintId: "mechanical.pulley_arrangement",
    mode: "both",
    parameters: { arrangement: "movable" },
    labels: [],
    revealProps: {},
  },
  {
    variantId: "visual-contract.resistivity-length-area-dimensions@1::comparison=length,mode=both::both",
    contractId: "visual-contract.resistivity-length-area-dimensions",
    contractVersion: 1,
    diagramBlueprintId: "mechanical.resistivity_dimensions",
    mode: "both",
    parameters: { comparison: "length" },
    labels: [],
    revealProps: {},
  },
  {
    variantId: "visual-contract.resistivity-length-area-dimensions@1::comparison=area,mode=both::both",
    contractId: "visual-contract.resistivity-length-area-dimensions",
    contractVersion: 1,
    diagramBlueprintId: "mechanical.resistivity_dimensions",
    mode: "both",
    parameters: { comparison: "area" },
    labels: [],
    revealProps: {},
  },
  {
    variantId: "visual-contract.magnetic-pole-interaction@1::mode=teaching,pole_pairing=like_poles_facing,show_pole_force=true::teaching",
    contractId: "visual-contract.magnetic-pole-interaction",
    contractVersion: 1,
    diagramBlueprintId: "magnetic.pole_interaction",
    mode: "teaching",
    parameters: { pole_pairing: "like_poles_facing" },
    labels: [],
    revealProps: { show_pole_force: true },
  },
  {
    variantId: "visual-contract.magnetic-pole-interaction@1::mode=assessment,pole_pairing=like_poles_facing::assessment",
    contractId: "visual-contract.magnetic-pole-interaction",
    contractVersion: 1,
    diagramBlueprintId: "magnetic.pole_interaction",
    mode: "assessment",
    parameters: { pole_pairing: "like_poles_facing" },
    labels: [],
    revealProps: {},
  },
  {
    variantId: "visual-contract.magnetic-pole-interaction@1::mode=teaching,pole_pairing=unlike_poles_facing,show_pole_force=true::teaching",
    contractId: "visual-contract.magnetic-pole-interaction",
    contractVersion: 1,
    diagramBlueprintId: "magnetic.pole_interaction",
    mode: "teaching",
    parameters: { pole_pairing: "unlike_poles_facing" },
    labels: [],
    revealProps: { show_pole_force: true },
  },
  {
    variantId: "visual-contract.magnetic-pole-interaction@1::mode=assessment,pole_pairing=unlike_poles_facing::assessment",
    contractId: "visual-contract.magnetic-pole-interaction",
    contractVersion: 1,
    diagramBlueprintId: "magnetic.pole_interaction",
    mode: "assessment",
    parameters: { pole_pairing: "unlike_poles_facing" },
    labels: [],
    revealProps: {},
  },
  {
    variantId: "visual-contract.magnetic-flux-density-comparison@1::density_comparison=false,mode=both::both",
    contractId: "visual-contract.magnetic-flux-density-comparison",
    contractVersion: 1,
    diagramBlueprintId: "magnetic.flux_field_lines",
    mode: "both",
    parameters: { density_comparison: false },
    labels: [],
    revealProps: {},
  },
  {
    variantId: "visual-contract.magnetic-flux-density-comparison@1::density_comparison=true,mode=both::both",
    contractId: "visual-contract.magnetic-flux-density-comparison",
    contractVersion: 1,
    diagramBlueprintId: "magnetic.flux_field_lines",
    mode: "both",
    parameters: { density_comparison: true },
    labels: [],
    revealProps: {},
  },
  {
    variantId: "visual-contract.motional-emf-geometry@1::mode=both::both",
    contractId: "visual-contract.motional-emf-geometry",
    contractVersion: 1,
    diagramBlueprintId: "emf.motional_emf_geometry",
    mode: "both",
    parameters: {},
    labels: ["conductor"],
    revealProps: {},
  },
  {
    variantId: "visual-contract.ac-generator-rotating-loop@1::mode=both,rotation_phase=vertical::both",
    contractId: "visual-contract.ac-generator-rotating-loop",
    contractVersion: 1,
    diagramBlueprintId: "generator.rotating_loop",
    mode: "both",
    parameters: { rotation_phase: "vertical" },
    labels: [],
    revealProps: {},
  },
  {
    variantId: "visual-contract.ac-generator-rotating-loop@1::mode=both,rotation_phase=horizontal::both",
    contractId: "visual-contract.ac-generator-rotating-loop",
    contractVersion: 1,
    diagramBlueprintId: "generator.rotating_loop",
    mode: "both",
    parameters: { rotation_phase: "horizontal" },
    labels: [],
    revealProps: {},
  },
  {
    variantId: "visual-contract.electronic-component-symbol-card@1::component_type=resistor,mode=both::both",
    contractId: "visual-contract.electronic-component-symbol-card",
    contractVersion: 1,
    diagramBlueprintId: "electronics.component_symbol_card",
    mode: "both",
    parameters: { component_type: "resistor" },
    labels: [],
    revealProps: {},
  },
  {
    variantId: "visual-contract.electronic-component-symbol-card@1::component_type=capacitor,mode=both::both",
    contractId: "visual-contract.electronic-component-symbol-card",
    contractVersion: 1,
    diagramBlueprintId: "electronics.component_symbol_card",
    mode: "both",
    parameters: { component_type: "capacitor" },
    labels: [],
    revealProps: {},
  },
  {
    variantId: "visual-contract.electronic-component-symbol-card@1::component_type=diode,mode=both::both",
    contractId: "visual-contract.electronic-component-symbol-card",
    contractVersion: 1,
    diagramBlueprintId: "electronics.component_symbol_card",
    mode: "both",
    parameters: { component_type: "diode" },
    labels: [],
    revealProps: {},
  },
  {
    variantId: "visual-contract.electronic-component-symbol-card@1::component_type=zener_diode,mode=both::both",
    contractId: "visual-contract.electronic-component-symbol-card",
    contractVersion: 1,
    diagramBlueprintId: "electronics.component_symbol_card",
    mode: "both",
    parameters: { component_type: "zener_diode" },
    labels: [],
    revealProps: {},
  },
  {
    variantId: "visual-contract.electronic-component-symbol-card@1::component_type=led,mode=both::both",
    contractId: "visual-contract.electronic-component-symbol-card",
    contractVersion: 1,
    diagramBlueprintId: "electronics.component_symbol_card",
    mode: "both",
    parameters: { component_type: "led" },
    labels: [],
    revealProps: {},
  },
  {
    variantId: "visual-contract.electronic-component-symbol-card@1::component_type=photodiode,mode=both::both",
    contractId: "visual-contract.electronic-component-symbol-card",
    contractVersion: 1,
    diagramBlueprintId: "electronics.component_symbol_card",
    mode: "both",
    parameters: { component_type: "photodiode" },
    labels: [],
    revealProps: {},
  },
  {
    variantId: "visual-contract.electronic-component-symbol-card@1::component_type=thermistor,mode=both::both",
    contractId: "visual-contract.electronic-component-symbol-card",
    contractVersion: 1,
    diagramBlueprintId: "electronics.component_symbol_card",
    mode: "both",
    parameters: { component_type: "thermistor" },
    labels: [],
    revealProps: {},
  },
  {
    variantId: "visual-contract.electronic-component-symbol-card@1::component_type=diac,mode=both::both",
    contractId: "visual-contract.electronic-component-symbol-card",
    contractVersion: 1,
    diagramBlueprintId: "electronics.component_symbol_card",
    mode: "both",
    parameters: { component_type: "diac" },
    labels: [],
    revealProps: {},
  },
  {
    variantId: "visual-contract.electronic-component-symbol-card@1::component_type=triac,mode=both::both",
    contractId: "visual-contract.electronic-component-symbol-card",
    contractVersion: 1,
    diagramBlueprintId: "electronics.component_symbol_card",
    mode: "both",
    parameters: { component_type: "triac" },
    labels: [],
    revealProps: {},
  },
  {
    variantId: "visual-contract.electronic-component-symbol-card@1::component_type=transistor,mode=both::both",
    contractId: "visual-contract.electronic-component-symbol-card",
    contractVersion: 1,
    diagramBlueprintId: "electronics.component_symbol_card",
    mode: "both",
    parameters: { component_type: "transistor" },
    labels: [],
    revealProps: {},
  },
  {
    variantId: "visual-contract.electronic-component-symbol-card@1::component_type=thyristor_scr,mode=both::both",
    contractId: "visual-contract.electronic-component-symbol-card",
    contractVersion: 1,
    diagramBlueprintId: "electronics.component_symbol_card",
    mode: "both",
    parameters: { component_type: "thyristor_scr" },
    labels: [],
    revealProps: {},
  },
  {
    variantId: "visual-contract.electronic-component-symbol-card@1::component_type=rectifier,mode=both::both",
    contractId: "visual-contract.electronic-component-symbol-card",
    contractVersion: 1,
    diagramBlueprintId: "electronics.component_symbol_card",
    mode: "both",
    parameters: { component_type: "rectifier" },
    labels: [],
    revealProps: {},
  },
  {
    variantId: "visual-contract.electronic-component-symbol-card@1::component_type=inverter,mode=both::both",
    contractId: "visual-contract.electronic-component-symbol-card",
    contractVersion: 1,
    diagramBlueprintId: "electronics.component_symbol_card",
    mode: "both",
    parameters: { component_type: "inverter" },
    labels: [],
    revealProps: {},
  },
];
