/**
 * CC-05D: mechanical governance/QA gate for instructional-visual semantic
 * contracts. Independently recomputes every count from the live CC-05A
 * corpus and the live CC-05D contract/canonical-variant data -- never
 * trusts a record's own claims, the same discipline
 * scripts/content/validate-pedagogy.ts already uses.
 *
 * Design authority: docs/architecture/CC-05D-INSTRUCTIONAL-VISUAL-
 * GOVERNANCE-AND-SEMANTIC-QA.md §E.
 *
 * Usage:
 *   node scripts/visual-governance/check-visual-governance.ts            (report)
 *   node scripts/visual-governance/check-visual-governance.ts --check     (exit 1 on any failure)
 */

import { existsSync, readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

import { pedagogyManifestSchema, visualSemanticContractSchema } from "@alp/content-schema";

import { cc05aPedagogyUnit202 } from "../content/data/cc05a-pedagogy-unit202.ts";
import { visualSemanticContracts } from "./data/cc05d-visual-contracts-unit202.ts";
import { CANONICAL_VARIANT_BUILDERS } from "./data/canonical-variants.ts";
import { checkCurrentArrowGeometry } from "./artifact-geometry-check.ts";

/**
 * Diagram blueprint ids with a real apps/mobile renderer component,
 * mirroring the shared registry in
 * apps/mobile/src/components/diagrams/DiagramRenderer.tsx (CC-11 -- the
 * single generic dispatch point the Lesson Player and any future
 * practice surface both use). This is a manually-maintained mirror (the
 * same pattern as the CC-05C proving-content fixture) because
 * scripts/content tooling must never import apps/mobile code (repository
 * boundary rule) -- so this list, not a live import, is what "governed
 * pilot blueprint" means for CC-05D/CC-11.
 *
 * CC-11 closes the 3-blueprint renderer gap CC-05D tracked but
 * deliberately left open: `circuit.series_parallel_mixed`,
 * `graph.waveform_sine` and `instrument.measurement_connection` all now
 * have real renderers (SeriesParallelMixedCircuitDiagram.tsx,
 * WaveformSineDiagram.tsx, InstrumentConnectionDiagram.tsx) -- all 7
 * governed diagram blueprints are now rendered.
 */
export const RENDERED_DIAGRAM_BLUEPRINT_IDS = new Set([
  "circuit.series_resistors",
  "circuit.parallel_resistors",
  "circuit.series_parallel_mixed",
  "magnetic.field_conductor_direction",
  "motor.force_field_current",
  "graph.waveform_sine",
  "instrument.measurement_connection",
  // CC-11.3: whole-course instructional visual coverage closeout -- see
  // LeverDiagram.tsx/GearDiagram.tsx/PulleyDiagram.tsx/
  // ResistivityDimensionsDiagram.tsx/MagneticPoleDiagram.tsx/
  // MagneticFluxDiagram.tsx/MotionalEmfDiagram.tsx/ACGeneratorDiagram.tsx/
  // ComponentSymbolCard.tsx, all registered in DiagramRenderer.tsx.
  "mechanical.lever_arrangement",
  "mechanical.gear_mesh",
  "mechanical.pulley_arrangement",
  "mechanical.resistivity_dimensions",
  "magnetic.pole_interaction",
  "magnetic.flux_field_lines",
  "emf.motional_emf_geometry",
  "generator.rotating_loop",
  "electronics.component_symbol_card",
]);

/**
 * DiagramBlueprint parameter values that are governed/declared but
 * deliberately never generated by the engine -- documented CC-05B
 * scoping decisions, not defects. Excluded from variant-coverage
 * expectations so this check never demands coverage of an image the
 * platform can never actually produce. See
 * packages/calculation-engine/src/families/magnetism.ts header comment.
 */
const DOCUMENTED_UNREACHABLE_PARAMETER_VALUES: Record<string, Record<string, unknown[]>> = {
  "magnetic.field_conductor_direction": { current_direction: ["left_to_right"] },
};

export interface VisualGovernanceReport {
  totalRealDiagramBlueprints: number;
  totalContracts: number;
  duplicateContractIds: string[];
  orphanContracts: string[];
  danglingAssertionFamilyRefs: string[];
  danglingCapabilityRefs: string[];
  danglingQuestionBlueprintRefs: string[];
  rendererCoverage: Array<{ blueprintId: string; rendererPresent: boolean; contractPresent: boolean }>;
  governedPilotBlueprintsMissingContract: string[];
  ungovernedNonPilotBlueprints: string[];
  incompleteVariantCoverage: string[];
  answerLeakageFailures: string[];
  totalCanonicalVariants: number;
  artifactGeometryChecked: number;
  artifactGeometryFailures: string[];
}

/**
 * If rendered artefacts already exist (npm run visuals:render has been
 * run), independently re-proves the current-direction arrow geometry
 * invariant against the ACTUAL rendered SVG bytes on disk (see
 * artifact-geometry-check.ts). Purely informational (0 checked, not a
 * failure) when no renders exist yet -- this check never requires
 * rendering to have happened first, so `npm run visuals:check` stays
 * runnable standalone.
 */
function checkRenderedArtifactGeometry(): { checked: number; failures: string[] } {
  const rendersDir = join(import.meta.dirname, "..", "..", "reports", "instructional-visuals", "renders");
  if (!existsSync(rendersDir)) return { checked: 0, failures: [] };

  const failures: string[] = [];
  let checked = 0;
  for (const file of readdirSync(rendersDir)) {
    if (!file.endsWith(".svg")) continue;
    const svg = readFileSync(join(rendersDir, file), "utf8");
    const result = checkCurrentArrowGeometry(svg);
    checked += result.checkedArrows;
    for (const failure of result.failures) failures.push(`${file}: ${failure}`);
  }
  return { checked, failures };
}

function buildReport(): VisualGovernanceReport {
  const pedagogy = pedagogyManifestSchema.parse(cc05aPedagogyUnit202);
  const contracts = visualSemanticContracts.map((c) => visualSemanticContractSchema.parse(c));

  const realDiagramBlueprintIds = new Set(pedagogy.diagramBlueprints.map((d) => d.id));
  const realAssertionFamilyIds = new Set(pedagogy.assertionFamilies.map((f) => f.id));
  const realCapabilityIds = new Set(pedagogy.capabilities.map((c) => c.id));
  const realQuestionBlueprintIds = new Set(pedagogy.questionBlueprints.map((q) => q.id));

  const seenContractIds = new Set<string>();
  const duplicateContractIds: string[] = [];
  const orphanContracts: string[] = [];
  const danglingAssertionFamilyRefs: string[] = [];
  const danglingCapabilityRefs: string[] = [];
  const danglingQuestionBlueprintRefs: string[] = [];

  for (const contract of contracts) {
    const key = `${contract.id}@${contract.version}`;
    if (seenContractIds.has(key)) duplicateContractIds.push(key);
    seenContractIds.add(key);

    if (!realDiagramBlueprintIds.has(contract.diagramBlueprintId)) {
      orphanContracts.push(`${contract.id} -> unknown diagramBlueprintId ${contract.diagramBlueprintId}`);
    }
    for (const familyId of contract.assertionFamilyIds) {
      if (!realAssertionFamilyIds.has(familyId)) danglingAssertionFamilyRefs.push(`${contract.id} -> unknown assertionFamilyId ${familyId}`);
    }
    for (const capabilityId of contract.capabilityIds) {
      if (!realCapabilityIds.has(capabilityId)) danglingCapabilityRefs.push(`${contract.id} -> unknown capabilityId ${capabilityId}`);
    }
    for (const questionBlueprintId of contract.relevantQuestionBlueprintIds) {
      if (!realQuestionBlueprintIds.has(questionBlueprintId)) {
        danglingQuestionBlueprintRefs.push(`${contract.id} -> unknown questionBlueprintId ${questionBlueprintId}`);
      }
    }
  }

  const contractByBlueprintId = new Map(contracts.map((c) => [c.diagramBlueprintId, c]));
  const rendererCoverage = [...realDiagramBlueprintIds].sort().map((blueprintId) => ({
    blueprintId,
    rendererPresent: RENDERED_DIAGRAM_BLUEPRINT_IDS.has(blueprintId),
    contractPresent: contractByBlueprintId.has(blueprintId),
  }));

  const governedPilotBlueprintsMissingContract = rendererCoverage
    .filter((r) => r.rendererPresent && !r.contractPresent)
    .map((r) => r.blueprintId);
  const ungovernedNonPilotBlueprints = rendererCoverage.filter((r) => !r.rendererPresent).map((r) => r.blueprintId);

  const diagramBlueprintById = new Map(pedagogy.diagramBlueprints.map((d) => [d.id, d]));
  const incompleteVariantCoverage: string[] = [];
  const answerLeakageFailures: string[] = [];
  let totalCanonicalVariants = 0;

  for (const contract of contracts) {
    const builder = CANONICAL_VARIANT_BUILDERS[contract.diagramBlueprintId];
    if (!builder) {
      incompleteVariantCoverage.push(`${contract.id}: no canonical-variant builder registered for ${contract.diagramBlueprintId}`);
      continue;
    }
    const variants = builder(contract.id, contract.version);
    totalCanonicalVariants += variants.length;

    const blueprint = diagramBlueprintById.get(contract.diagramBlueprintId);
    if (blueprint) {
      const unreachable = DOCUMENTED_UNREACHABLE_PARAMETER_VALUES[contract.diagramBlueprintId] ?? {};
      for (const param of blueprint.parameters) {
        if (param.kind !== "enum" || !param.allowed) continue;
        const documentedGap = new Set(unreachable[param.name] ?? []);
        const expectedValues = param.allowed.filter((v) => !documentedGap.has(v));
        const observedValues = new Set(variants.map((v) => v.parameters[param.name]));
        const missing = expectedValues.filter((v) => !observedValues.has(v));
        if (missing.length > 0) {
          incompleteVariantCoverage.push(`${contract.id}: parameter ${param.name} missing canonical coverage for values [${missing.join(", ")}]`);
        }
      }
    }

    for (const rule of contract.answerDisclosure) {
      for (const v of variants) {
        const isRevealed = Object.keys(v.revealProps).length > 0;
        if (v.mode === "assessment" && isRevealed) {
          answerLeakageFailures.push(`${contract.id}/${v.variantId}: assessment-mode variant carries non-empty revealProps for '${rule.element}'`);
        }
        if (v.mode === "teaching" && rule.revealedInModes.includes("teaching") && !isRevealed) {
          answerLeakageFailures.push(`${contract.id}/${v.variantId}: teaching-mode variant should reveal '${rule.element}' but revealProps is empty`);
        }
      }
    }
  }

  const artifactGeometry = checkRenderedArtifactGeometry();

  return {
    totalRealDiagramBlueprints: realDiagramBlueprintIds.size,
    totalContracts: contracts.length,
    duplicateContractIds,
    orphanContracts,
    danglingAssertionFamilyRefs,
    danglingCapabilityRefs,
    danglingQuestionBlueprintRefs,
    rendererCoverage,
    governedPilotBlueprintsMissingContract,
    ungovernedNonPilotBlueprints,
    incompleteVariantCoverage,
    answerLeakageFailures,
    totalCanonicalVariants,
    artifactGeometryChecked: artifactGeometry.checked,
    artifactGeometryFailures: artifactGeometry.failures,
  };
}

function formatReport(report: VisualGovernanceReport): string {
  const lines: string[] = [];
  lines.push("CC-05D instructional-visual governance mechanical report");
  lines.push("==========================================================");
  lines.push(`Real governed diagram blueprints (CC-05A corpus): ${report.totalRealDiagramBlueprints}`);
  lines.push(`Visual semantic contracts (CC-05D): ${report.totalContracts}`);
  lines.push(`Canonical audit variants: ${report.totalCanonicalVariants}`);
  lines.push("");
  lines.push("Renderer / contract coverage per governed diagram blueprint:");
  for (const r of report.rendererCoverage) {
    lines.push(`  - ${r.blueprintId}: renderer=${r.rendererPresent ? "present" : "MISSING"}, contract=${r.contractPresent ? "present" : "MISSING"}`);
  }
  lines.push("");
  lines.push(`Ungoverned-renderer blueprints (tracked gap, non-fatal, out of CC-05D scope -- target: informational only): ${report.ungovernedNonPilotBlueprints.length}`);
  if (report.ungovernedNonPilotBlueprints.length) lines.push(`    ${report.ungovernedNonPilotBlueprints.join(", ")}`);
  lines.push(`Governed PILOT blueprints missing a contract (target 0, FATAL): ${report.governedPilotBlueprintsMissingContract.length}`);
  if (report.governedPilotBlueprintsMissingContract.length) lines.push(`    ${report.governedPilotBlueprintsMissingContract.join(", ")}`);
  lines.push(`Duplicate contract ids (target 0): ${report.duplicateContractIds.length}`);
  if (report.duplicateContractIds.length) lines.push(`    ${report.duplicateContractIds.join(", ")}`);
  lines.push(`Orphan contracts -- unknown diagramBlueprintId (target 0): ${report.orphanContracts.length}`);
  if (report.orphanContracts.length) lines.push(`    ${report.orphanContracts.join("; ")}`);
  lines.push(`Dangling assertion-family references (target 0): ${report.danglingAssertionFamilyRefs.length}`);
  if (report.danglingAssertionFamilyRefs.length) lines.push(`    ${report.danglingAssertionFamilyRefs.join("; ")}`);
  lines.push(`Dangling capability references (target 0): ${report.danglingCapabilityRefs.length}`);
  if (report.danglingCapabilityRefs.length) lines.push(`    ${report.danglingCapabilityRefs.join("; ")}`);
  lines.push(`Dangling question-blueprint references (target 0): ${report.danglingQuestionBlueprintRefs.length}`);
  if (report.danglingQuestionBlueprintRefs.length) lines.push(`    ${report.danglingQuestionBlueprintRefs.join("; ")}`);
  lines.push(`Incomplete canonical-variant coverage (target 0): ${report.incompleteVariantCoverage.length}`);
  if (report.incompleteVariantCoverage.length) lines.push(`    ${report.incompleteVariantCoverage.join("; ")}`);
  lines.push(`Answer-leakage / disclosure failures (target 0): ${report.answerLeakageFailures.length}`);
  if (report.answerLeakageFailures.length) lines.push(`    ${report.answerLeakageFailures.join("; ")}`);
  lines.push(`Rendered-artefact current-arrow geometry checked (informational, requires 'npm run visuals:render' to have run): ${report.artifactGeometryChecked} arrows`);
  lines.push(`  - failures (target 0): ${report.artifactGeometryFailures.length}`);
  if (report.artifactGeometryFailures.length) lines.push(`    ${report.artifactGeometryFailures.join("; ")}`);
  return lines.join("\n");
}

export function isReportClean(report: VisualGovernanceReport): boolean {
  return (
    report.duplicateContractIds.length === 0 &&
    report.orphanContracts.length === 0 &&
    report.danglingAssertionFamilyRefs.length === 0 &&
    report.danglingCapabilityRefs.length === 0 &&
    report.danglingQuestionBlueprintRefs.length === 0 &&
    report.governedPilotBlueprintsMissingContract.length === 0 &&
    report.incompleteVariantCoverage.length === 0 &&
    report.answerLeakageFailures.length === 0 &&
    report.artifactGeometryFailures.length === 0
  );
}

export { buildReport, formatReport };

function isMainModule(): boolean {
  const entryPoint = process.argv[1];
  if (!entryPoint) return false;
  return fileURLToPath(import.meta.url) === entryPoint;
}

if (isMainModule()) {
  const report = buildReport();
  console.log(formatReport(report));
  const clean = isReportClean(report);
  console.log("");
  console.log(clean ? "PASS: all mandatory visual-governance gates are zero." : "FAIL: one or more mandatory visual-governance gates are non-zero.");
  if (process.argv.includes("--check") && !clean) {
    process.exit(1);
  }
}
