/**
 * CC-11.1 (task sections 9-10): builds a portable, self-contained review
 * artefact for EXTERNAL pixel-level inspection of every canonical Unit
 * 202 instructional-visual variant -- something a PO/Architect can open
 * (or upload to a vision-capable reviewer) WITHOUT running the app or
 * this repository at all.
 *
 * The HTML catalogue (reports/instructional-visuals/index.html,
 * generated by generate-report.ts) already carries full traceability
 * for interactive, in-repo review. This script produces the SEPARATE,
 * portable artefact the task brief asks for: one PDF contact sheet,
 * one page per canonical variant, at a realistic mobile viewport width,
 * each page captioned with the same governance metadata (diagram/
 * contract id, instructional purpose, linked assertion family/
 * capability/assertion identifiers, TEACHING/ASSESSMENT/BOTH mode
 * state, and the semantic contract's mustShow/mustNotShow
 * requirements) so a reviewer never has to cross-reference this
 * repository to understand what they are looking at.
 *
 * This produces a REAL, uploadable artefact for a human or external
 * vision-model reviewer to inspect -- it does NOT itself perform any
 * semantic/visual review. See generate-report.ts's "TRUTHFULNESS
 * CORRECTION" comment: nothing in this file may ever claim these
 * images have been visually approved.
 *
 * Usage:
 *   npm run visuals:review:package
 * (requires reports/instructional-visuals/{manifest,mechanical-audit,
 * semantic-audit}.json to already exist -- run `npm run visuals:all`
 * first if they are missing or stale)
 */

import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { join } from "node:path";
import { tmpdir } from "node:os";

import { chromium } from "@playwright/test";

import { generateReport } from "./generate-report.ts";

const REPORTS_DIR = join(import.meta.dirname, "..", "..", "reports", "instructional-visuals");
const REVIEW_PACKAGE_DIR = join(REPORTS_DIR, "review-package");
const PDF_PATH = join(REVIEW_PACKAGE_DIR, "unit202-instructional-visuals-review.pdf");
const MANIFEST_PATH = join(REVIEW_PACKAGE_DIR, "manifest.json");

function esc(text: string): string {
  return text.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

function modeLabel(mode: string): string {
  if (mode === "teaching") return "TEACHING";
  if (mode === "assessment") return "ASSESSMENT";
  return "TEACHING + ASSESSMENT (both)";
}

function pageHtml(card: ReturnType<typeof generateReport>["cards"][number], pageNumber: number, totalPages: number): string {
  const svgPath = join(REPORTS_DIR, card.svgRelativePath);
  const svg = existsSync(svgPath) ? readFileSync(svgPath, "utf8") : "<p>MISSING RENDERED ARTEFACT</p>";

  return `
<section class="sheet">
  <div class="sheet-header">
    <div class="page-no">Variant ${pageNumber} of ${totalPages}</div>
    <div class="mode-badge mode-${esc(card.mode)}">${modeLabel(card.mode)}</div>
  </div>
  <h2>${esc(card.teachingIntent)}</h2>
  <div class="phone-frame">
    <div class="phone-screen">${svg}</div>
  </div>
  <dl>
    <dt>Diagram blueprint</dt><dd><code>${esc(card.diagramBlueprintId)}</code> (${esc(card.diagramType)})</dd>
    <dt>Visual semantic contract</dt><dd><code>${esc(card.contractId)}</code></dd>
    <dt>Canonical variant id</dt><dd class="small"><code>${esc(card.variantId)}</code></dd>
    <dt>Linked assertion family</dt><dd>${card.assertionFamilyIds.map(esc).join(", ") || "&mdash;"}</dd>
    <dt>Linked assertion identifiers</dt><dd>${card.assertionIdentifiers.map(esc).join(", ") || "&mdash;"}</dd>
    <dt>Linked capability</dt><dd>${card.capabilityIds.map(esc).join(", ") || "&mdash;"}</dd>
    <dt>Representation role</dt><dd>${esc(card.representationRole)}</dd>
  </dl>
  <div class="contract-reqs">
    <div>
      <h3>Must show</h3>
      <ul>${card.mustShow.map((s) => `<li>${esc(s)}</li>`).join("")}</ul>
    </div>
    <div>
      <h3>Must NOT show</h3>
      <ul>${card.mustNotShow.length ? card.mustNotShow.map((s) => `<li>${esc(s)}</li>`).join("") : "<li>&mdash;</li>"}</ul>
    </div>
  </div>
</section>`;
}

function coverHtml(cardCount: number): string {
  return `
<section class="sheet cover">
  <h1>Unit 202 &mdash; Instructional Visual Review Package</h1>
  <p class="generated">Generated ${new Date().toISOString()}</p>
  <p>${cardCount} canonical instructional-visual variants, one per page, at a realistic mobile viewport width (390px).</p>
  <div class="notice">
    <strong>This package is for REAL, human/external pixel-level review.</strong>
    No image in this package has been visually approved by this repository's tooling.
    Any "SIMULATED SEMANTIC" result referenced elsewhere in this project's reports comes
    from a deterministic mock pipeline that proves the QA architecture works end-to-end --
    it is not a substitute for the review this package exists to support.
  </div>
  <p>Each page shows: the actual rendered instructional SVG at mobile scale, its governed
  instructional purpose, which assessment-obligation/assertion/capability it is linked to,
  its TEACHING / ASSESSMENT / BOTH state, and the semantic contract's must-show / must-not-show
  requirements it is being checked against.</p>
</section>`;
}

function buildDocumentHtml(cards: ReturnType<typeof generateReport>["cards"]): string {
  const pages = cards.map((card, i) => pageHtml(card, i + 1, cards.length)).join("\n");
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>Unit 202 Instructional Visual Review Package</title>
<style>
  * { box-sizing: border-box; }
  body { margin: 0; font-family: system-ui, -apple-system, "Segoe UI", sans-serif; color: #16181d; background: #fff; }
  .sheet { page-break-after: always; padding: 28px 32px; min-height: 90vh; }
  .sheet:last-child { page-break-after: auto; }
  .cover { display: flex; flex-direction: column; justify-content: center; gap: 14px; }
  .cover h1 { font-size: 26px; margin: 0; }
  .cover .generated { color: #666; font-size: 12px; }
  .notice { border: 1px solid #8a5cf6; background: #f4effe; color: #4a2d99; border-radius: 10px; padding: 14px 16px; font-size: 13px; line-height: 1.5; }
  .sheet-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 6px; }
  .page-no { font-size: 12px; color: #888; }
  .mode-badge { font-size: 11px; font-weight: 700; padding: 3px 10px; border-radius: 999px; border: 1px solid #999; }
  .mode-badge.mode-teaching { color: #1a7f37; border-color: #1a7f37; }
  .mode-badge.mode-assessment { color: #b35900; border-color: #b35900; }
  .mode-badge.mode-both { color: #1f5fb3; border-color: #1f5fb3; }
  h2 { font-size: 16px; margin: 4px 0 12px; }
  .phone-frame { width: 390px; margin: 0 auto 16px; border: 3px solid #222; border-radius: 28px; padding: 10px; background: #fafafa; }
  .phone-screen { width: 100%; background: #ffffff; border-radius: 16px; overflow: hidden; display: flex; align-items: center; justify-content: center; padding: 8px; }
  .phone-screen svg { max-width: 100%; height: auto; }
  dl { display: grid; grid-template-columns: 190px 1fr; gap: 4px 10px; font-size: 12px; margin: 10px 0; }
  dt { color: #666; }
  dd { margin: 0; }
  dd.small code, dd code { word-break: break-all; font-size: 11px; }
  .contract-reqs { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin-top: 10px; }
  .contract-reqs h3 { font-size: 12px; text-transform: uppercase; letter-spacing: 0.04em; color: #444; margin: 0 0 4px; }
  .contract-reqs ul { margin: 0; padding-left: 18px; font-size: 12px; line-height: 1.5; }
</style>
</head>
<body>
${coverHtml(cards.length)}
${pages}
</body>
</html>`;
}

async function main(): Promise<void> {
  const { cards } = generateReport();
  mkdirSync(REVIEW_PACKAGE_DIR, { recursive: true });

  const html = buildDocumentHtml(cards);
  const scratchDir = mkdtempSync(join(tmpdir(), "unit202-visual-review-"));
  const tempHtmlPath = join(scratchDir, "_source.html");
  writeFileSync(tempHtmlPath, html, "utf8");

  const browser = await chromium.launch();
  try {
    const page = await browser.newPage();
    await page.goto(`file://${tempHtmlPath.replace(/\\/g, "/")}`);
    await page.pdf({
      path: PDF_PATH,
      format: "A4",
      printBackground: true,
      margin: { top: "10mm", bottom: "10mm", left: "10mm", right: "10mm" },
    });
  } finally {
    await browser.close();
    rmSync(scratchDir, { recursive: true, force: true });
  }

  writeFileSync(
    MANIFEST_PATH,
    JSON.stringify(
      {
        generatedAt: new Date().toISOString(),
        pdf: "unit202-instructional-visuals-review.pdf",
        pageOrder: cards.map((c, i) => ({ page: i + 2, variantId: c.variantId, contractId: c.contractId, mode: c.mode })),
      },
      null,
      2,
    ) + "\n",
    "utf8",
  );

  console.log(`Review package generated: ${cards.length} variants, ${cards.length + 1} PDF pages (1 cover + ${cards.length} variants).`);
  console.log(`  PDF: ${PDF_PATH}`);
  console.log(`  Manifest: ${MANIFEST_PATH}`);
}

function isMainModule(): boolean {
  const entryPoint = process.argv[1];
  if (!entryPoint) return false;
  return fileURLToPath(import.meta.url) === entryPoint;
}

if (isMainModule()) {
  main().catch((error: unknown) => {
    console.error(error);
    process.exitCode = 1;
  });
}
